"""Direct, retrospective evidence of AI coding-tool usage in the 490
vintage-cohort packages -- not the AI/genAI *SDK-dependency* proxy from
deps_time_analysis.py (which measures what a package is ABOUT), but
whether the package's own git history shows a tool actually being used to
write it.

Two signal types, both read straight from git objects already reachable
via clone_url + snapshot_sha in output/vintage/packages.csv (re-clones
--no-checkout, same discipline as every other extractor here):

  1. Commit trailers/messages that self-identify an AI tool -- the same
     "Co-Authored-By: Claude" convention visible in this very project's own
     commit history. Scanned across the package's FULL history up to its
     snapshot commit, not just a window.
  2. Config/instruction files a repo carries for a specific AI tool to
     read (CLAUDE.md, .cursorrules, .github/copilot-instructions.md, ...)
     -- presence checked at the snapshot, same as the manifest/package
     checks elsewhere in this project.

Both are STRONG-SIGNAL, LOW-RECALL by construction: a real positive here
is solid evidence (nobody accidentally writes "Co-Authored-By: Claude"),
but silence proves nothing -- most AI-assisted commits (autocomplete,
copy-pasted suggestions, chat-assisted edits made through a human's own
git identity) leave no trace at all. This measures *self-disclosed* usage,
not true usage, and different tools self-disclose at very different rates
by default (Claude Code always adds a trailer; most Copilot autocomplete
commits add none) -- see the report for the full caveat.
"""
from __future__ import annotations

import csv
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

ROOT = Path(__file__).resolve().parent.parent
VINTAGE_DIR = ROOT / "output" / "vintage"
AI_SIGNAL_DIR = ROOT / "output" / "ai_signal"
CLONES_DIR = ROOT / "clones-ai-signal"

CLONE_TIMEOUT_S = 180

_REC_SEP = "\x02"
_FIELD_SEP = "\x01"

# Strong signal only: an explicit co-authorship/generation trailer naming
# the tool, not a bare mention of the word (avoids false positives like a
# repo whose own subject matter happens to be "a copilot for X").
AI_TOOL_PATTERNS = {
    "claude": re.compile(
        r"co-authored-by:\s*claude|generated with.*claude code|claude\.ai/code", re.I
    ),
    "copilot": re.compile(
        r"co-authored-by:.*copilot|generated by github copilot|copilot-workspace", re.I
    ),
    "cursor": re.compile(r"co-authored-by:.*cursor", re.I),
    "chatgpt_openai_codex": re.compile(
        r"co-authored-by:.*(chatgpt|openai|codex)|generated (by|with) chatgpt", re.I
    ),
    "devin": re.compile(r"co-authored-by:.*devin", re.I),
    "gemini": re.compile(r"co-authored-by:.*gemini", re.I),
    "amazon_q": re.compile(r"co-authored-by:.*amazon.?q", re.I),
    "windsurf": re.compile(r"co-authored-by:.*windsurf", re.I),
    "replit": re.compile(r"co-authored-by:.*replit", re.I),
    "aider": re.compile(r"co-authored-by:.*aider", re.I),
}

# Root-level filename or path-prefix markers a repo carries for an AI tool
# to read as project-specific instructions.
MARKER_FILES = {"CLAUDE.md", "GEMINI.md", "AGENTS.md", ".cursorrules", ".windsurfrules",
                 ".aider.conf.yml", ".github/copilot-instructions.md"}
MARKER_DIR_PREFIXES = (".claude/", ".cursor/", ".continue/", ".windsurf/")

ROW_FIELDNAMES = [
    "repo_full_name", "vintage_quarter", "snapshot_sha",
    "total_commits", "ai_commits", "ai_commit_fraction",
    "tools_matched", "first_ai_commit_date",
    "marker_files_found",
]


def log(msg: str) -> None:
    from datetime import datetime
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)


def check_marker_files(repo_dir: str, sha: str) -> list[str]:
    paths = subprocess.check_output(
        ["git", "-C", repo_dir, "ls-tree", "-r", "--name-only", sha], text=True
    ).splitlines()
    found = [p for p in paths if p in MARKER_FILES or p.startswith(MARKER_DIR_PREFIXES)]
    return sorted(set(found))


def scan_commit_messages(repo_dir: str, sha: str) -> dict:
    fmt = f"{_REC_SEP}%aI{_FIELD_SEP}%B"
    out = subprocess.check_output(
        ["git", "-C", repo_dir, "log", f"--format={fmt}", sha],
        text=True, errors="replace",
    )
    records = [r for r in out.split(_REC_SEP) if r.strip()]

    total = 0
    ai_commits = 0
    tools_matched: set[str] = set()
    first_ai_date: Optional[str] = None

    for rec in records:
        total += 1
        date, _, body = rec.partition(_FIELD_SEP)
        hit_this_commit = False
        for tool, pattern in AI_TOOL_PATTERNS.items():
            if pattern.search(body):
                tools_matched.add(tool)
                hit_this_commit = True
        if hit_this_commit:
            ai_commits += 1
            if first_ai_date is None or date < first_ai_date:
                first_ai_date = date

    return {
        "total_commits": total,
        "ai_commits": ai_commits,
        "ai_commit_fraction": (ai_commits / total) if total else 0.0,
        "tools_matched": ";".join(sorted(tools_matched)),
        "first_ai_commit_date": first_ai_date or "",
    }


def process_one(row: pd.Series) -> Optional[dict]:
    full_name = row["repo_full_name"]
    safe_name = full_name.replace("/", "__")
    clone_dir = CLONES_DIR / safe_name
    if clone_dir.exists():
        shutil.rmtree(clone_dir)

    try:
        try:
            subprocess.run(
                ["git", "clone", "--no-checkout", "--quiet", row["clone_url"], str(clone_dir)],
                check=True, timeout=CLONE_TIMEOUT_S,
                stdout=subprocess.DEVNULL, stderr=subprocess.PIPE,
            )
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:
            log(f"  [warn] clone failed for {full_name}: {e}")
            return None

        sha = row["snapshot_sha"]
        markers = check_marker_files(str(clone_dir), sha)
        commit_stats = scan_commit_messages(str(clone_dir), sha)

        return {
            "repo_full_name": full_name,
            "vintage_quarter": row["vintage_quarter"],
            "snapshot_sha": sha,
            **commit_stats,
            "marker_files_found": ";".join(markers),
        }
    finally:
        if clone_dir.exists():
            shutil.rmtree(clone_dir)


def main() -> None:
    AI_SIGNAL_DIR.mkdir(parents=True, exist_ok=True)
    CLONES_DIR.mkdir(parents=True, exist_ok=True)
    out_path = AI_SIGNAL_DIR / "ai_signals.csv"

    pkgs = pd.read_csv(VINTAGE_DIR / "packages.csv")
    log(f"Scanning {len(pkgs)} packages for AI-tool commit/marker-file signals ...")

    with open(out_path, "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=ROW_FIELDNAMES)
        writer.writeheader()
        n_ai = 0
        for i, row in pkgs.iterrows():
            result = process_one(row)
            if result is None:
                continue
            writer.writerow(result)
            fh.flush()
            if result["ai_commits"] > 0 or result["marker_files_found"]:
                n_ai += 1
                log(f"  [{row['vintage_quarter']}] {row['repo_full_name']}: "
                    f"ai_commits={result['ai_commits']}/{result['total_commits']} "
                    f"tools={result['tools_matched']!r} markers={result['marker_files_found']!r}")
            if (i + 1) % 50 == 0:
                log(f"  {i + 1}/{len(pkgs)} processed, {n_ai} with any AI signal so far ...")

    log(f"Done. Wrote {out_path}. {n_ai}/{len(pkgs)} packages showed some AI-tool signal.")


if __name__ == "__main__":
    main()
