#!/usr/bin/env python3
"""Regenerate index.html from posts/*.md.

Each post is a markdown file with YAML frontmatter:

    ---
    title: "..."
    date: 2026-09-08T19:30:18+02:00
    abstract: >
      One or two sentences of framing -- what was measured, on what sample.
    key_results:
      - "Headline finding 1, quantified."
      - "Headline finding 2, quantified."
      - "Headline finding 3 (optional), quantified."
    links:
      - label: Full report
        path: ../repo-metrics/REPORT.md
    ---

    Optional longer body -- extra notes, caveats, bugs caught during
    validation. Rendered collapsed under "More notes" so the post itself
    stays a short abstract + 2-3 results, not the full report.

Run after adding/editing a post: `python3 build.py`.
"""
from __future__ import annotations

import html
import re
from datetime import datetime
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
POSTS_DIR = ROOT / "posts"
OUT_PATH = ROOT / "index.html"

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?\n)---\s*\n?(.*)$", re.DOTALL)


def load_post(path: Path) -> dict:
    text = path.read_text()
    m = FRONTMATTER_RE.match(text)
    if not m:
        raise ValueError(f"{path}: no YAML frontmatter found (must start with '---')")
    meta = yaml.safe_load(m.group(1)) or {}
    meta["body"] = m.group(2).strip()
    meta["_path"] = path
    if "title" not in meta or "date" not in meta:
        raise ValueError(f"{path}: frontmatter must have at least 'title' and 'date'")
    if "abstract" not in meta or "key_results" not in meta:
        raise ValueError(f"{path}: frontmatter must have 'abstract' and 'key_results'")
    if isinstance(meta["date"], str):
        meta["date"] = datetime.fromisoformat(meta["date"])
    return meta


def load_all_posts() -> list[dict]:
    posts = [load_post(p) for p in sorted(POSTS_DIR.glob("*.md"))]
    posts.sort(key=lambda p: p["date"], reverse=True)
    return posts


def inline_md(text: str) -> str:
    text = html.escape(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
    text = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', text)
    return text


def render_paragraphs(text: str) -> str:
    if not text:
        return ""
    paras = [p.strip() for p in text.split("\n\n") if p.strip()]
    return "\n".join(f"          <p>{inline_md(p)}</p>" for p in paras)


def render_key_results(items: list[str]) -> str:
    lis = "\n".join(f"          <li>{inline_md(item)}</li>" for item in items)
    return f'        <ul class="key-results">\n{lis}\n        </ul>'


def render_links(links: list[dict]) -> str:
    if not links:
        return ""
    buttons = "\n".join(
        f'          <a href="{html.escape(l["path"])}" class="btn btn-sm btn-outline-primary">{html.escape(l["label"])}</a>'
        for l in links
    )
    return f'        <div class="link-row">\n{buttons}\n        </div>'


def render_notes(body: str) -> str:
    if not body:
        return ""
    return (
        '        <details class="notes">\n'
        '          <summary>More notes</summary>\n'
        f"{render_paragraphs(body)}\n"
        "        </details>"
    )


POST_TEMPLATE = """    <article class="card post-card shadow-sm mb-4">
      <div class="card-body">
        <div class="post-meta">
          <time datetime="{iso}">{pretty}</time>
        </div>
        <h2 class="card-title h4">{title}</h2>
        <p class="abstract">{abstract}</p>
{key_results}
{links}
{notes}
      </div>
    </article>"""


def render_post(post: dict) -> str:
    return POST_TEMPLATE.format(
        iso=post["date"].isoformat(),
        pretty=post["date"].strftime("%B %-d, %Y"),
        title=inline_md(post["title"]),
        abstract=inline_md(post.get("abstract", "").strip()),
        key_results=render_key_results(post.get("key_results", [])),
        links=render_links(post.get("links", [])),
        notes=render_notes(post.get("body", "")),
    )


PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ChronoGit Research Diary</title>
<link rel="stylesheet" href="vendor/bootstrap-yeti.min.css">
<link rel="stylesheet" href="style.css">
</head>
<body>
  <nav class="navbar navbar-expand navbar-dark bg-primary mb-4">
    <div class="container">
      <span class="navbar-brand mb-0 h1">ChronoGit Research Diary</span>
    </div>
  </nav>
  <div class="container">
    <p class="tagline text-muted mb-4">Dated notes on the repo-metrics studies -- what was measured, what held up, what didn't.</p>
    <main>
{posts}
    </main>
    <footer class="text-muted small py-4">
      <p>Generated by <code>research-diary/build.py</code> from <code>posts/*.md</code>. {count} entries.</p>
    </footer>
  </div>
</body>
</html>
"""


def main() -> None:
    posts = load_all_posts()
    rendered = "\n\n".join(render_post(p) for p in posts)
    page = PAGE_TEMPLATE.format(posts=rendered, count=len(posts))
    OUT_PATH.write_text(page)
    print(f"Wrote {OUT_PATH} ({len(posts)} posts).")


if __name__ == "__main__":
    main()
