#!/usr/bin/env python3
"""Regenerate index.html from posts/*.md.

Each post is a markdown file with YAML frontmatter:

    ---
    title: "..."
    date: 2026-09-08T19:30:18+02:00
    summary: >
      One paragraph, folded YAML is fine.
    links:
      - label: Full report
        path: ../../repo-metrics/REPORT.md
    ---

    Optional body prose (plain paragraphs; **bold**, `code`, and
    [text](url) are supported).

Run after adding/editing a post: `python3 build.py`.
"""
from __future__ import annotations

import html
import re
from datetime import datetime
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
POSTS_DIR = ROOT / "posts"
OUT_PATH = ROOT / "index.html"

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?\n)---\s*\n?(.*)$", re.DOTALL)


def load_post(path: Path) -> dict:
    text = path.read_text()
    m = FRONTMATTER_RE.match(text)
    if not m:
        raise ValueError(f"{path}: no YAML frontmatter found (must start with '---')")
    meta = yaml.safe_load(m.group(1)) or {}
    meta["body"] = m.group(2).strip()
    meta["_path"] = path
    if "title" not in meta or "date" not in meta:
        raise ValueError(f"{path}: frontmatter must have at least 'title' and 'date'")
    if isinstance(meta["date"], str):
        meta["date"] = datetime.fromisoformat(meta["date"])
    return meta


def load_all_posts() -> list[dict]:
    posts = [load_post(p) for p in sorted(POSTS_DIR.glob("*.md"))]
    posts.sort(key=lambda p: p["date"], reverse=True)
    return posts


def inline_md(text: str) -> str:
    text = html.escape(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
    text = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', text)
    return text


def render_paragraphs(text: str) -> str:
    if not text:
        return ""
    paras = [p.strip() for p in text.split("\n\n") if p.strip()]
    return "\n".join(f"      <p>{inline_md(p)}</p>" for p in paras)


def render_links(links: list[dict]) -> str:
    if not links:
        return ""
    items = "\n".join(
        f'        <li><a href="{html.escape(l["path"])}">{html.escape(l["label"])}</a></li>'
        for l in links
    )
    return f'      <ul class="links">\n{items}\n      </ul>'


POST_TEMPLATE = """    <article class="post">
      <div class="meta">
        <time datetime="{iso}">{pretty}</time>
      </div>
      <h2>{title}</h2>
      <p class="summary">{summary}</p>
{body}
{links}
    </article>"""


def render_post(post: dict) -> str:
    return POST_TEMPLATE.format(
        iso=post["date"].isoformat(),
        pretty=post["date"].strftime("%B %-d, %Y"),
        title=inline_md(post["title"]),
        summary=inline_md(post.get("summary", "").strip()),
        body=render_paragraphs(post.get("body", "")),
        links=render_links(post.get("links", [])),
    )


PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ChronoGit Research Diary</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
  <header>
    <h1>ChronoGit Research Diary</h1>
    <p class="tagline">Dated notes on the repo-metrics studies -- what was measured, what held up, what didn't.</p>
  </header>
  <main>
{posts}
  </main>
  <footer>
    <p>Generated by <code>research-diary/build.py</code> from <code>posts/*.md</code>. {count} entries.</p>
  </footer>
</body>
</html>
"""


def main() -> None:
    posts = load_all_posts()
    rendered = "\n\n".join(render_post(p) for p in posts)
    page = PAGE_TEMPLATE.format(posts=rendered, count=len(posts))
    OUT_PATH.write_text(page)
    print(f"Wrote {OUT_PATH} ({len(posts)} posts).")


if __name__ == "__main__":
    main()
